Test1/api/urls.py
from django.urls import path, include
from .views import HomeView
urlpatterns = [
    path('',HomeView.as_view(),name ='home')
]

Test1/blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
)

app_name='blog'
urlpatterns = [
    path('posts/',PostListView.as_view(), name='post_list'),
    path('create-posts/',PostCreateView.as_view(), name='create_posts'),
    path('post-details/<int:pk>/', PostDetailView.as_view(), name='post_details'),
    path('post-update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

Test1/core/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    # path('ckeditor/',include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Test1/templates/base_extra/_base1.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://kit.fontawesome.com/78ceb0f66b.js" crossorigin="anonymous"></script>
    <title>
      {% block title %} {% endblock title %}  
    </title>
    <style>
      code {
        font-family: Consolas,"courier new";
        background-color:grey;
        padding: 2px;
        font-size: 105%;
      }
      </style>

  </head>
  <body>
    <header class="py-3 mb-4 border-bottom shadow">
      <div class="container-fluid align-items-center d-flex">
          <div class="flex-shrink-1">
              <a href="#" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none">
                  <i class="bi bi-bootstrap fs-2 text-dark"></i>
              </a>
          </div>
          <div class="flex-grow-1 d-flex align-items-center">
            <a href="#" data-bs-target="#sidebar" data-bs-toggle="collapse" class="border rounded-3 p-1 text-decoration-none"><i class="bi bi-list bi-lg py-2 p-1"></i> Menu</a>
          
              <form class="w-100 me-3">
                  <input type="search" class="form-control" placeholder="Search...">
              </form>
              <div class="flex-shrink-0 dropdown">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://ehsansoftware.com/img/team/nazmul.jpg" alt="user" width="32" height="32" class="rounded-circle">
                  </a>
                  <!-- <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="dropdownUser2" style=""> -->
                  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="dropdownUser2">
                      <li><a class="dropdown-item" href="#">New project...</a></li>
                      <li><a class="dropdown-item" href="#">Settings</a></li>
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li>
                          <hr class="dropdown-divider">
                      </li>
                      <li><a class="dropdown-item" href="#">Sign out</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </header>

  <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                    </li>
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">loser</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col py-3">
            Content area...
        </div>
    </div>
</div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block javascript %}
      <script src="{% static 'js/base.js' %}"></script>
    {% endblock javascript %}
  
  </body>
</html>

Test1/templates/base_extra/first_created_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
   
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://kit.fontawesome.com/78ceb0f66b.js" crossorigin="anonymous"></script>
    <title>
      {% block title %} {% endblock title %}  
    </title>
    <style>
      code {
        font-family: Consolas,"courier new";
        background-color:grey;
        padding: 2px;
        font-size: 105%;
      }
      </style>

  </head>
  <body>


    {% comment %}

    <header class="py-3 mb-4 border-bottom shadow">
      <div class="container-fluid align-items-center d-flex">
          <div class="flex-shrink-1">
              <a href="#" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none">
                  <i class="bi bi-bootstrap fs-2 text-dark"></i>
              </a>
          </div>
          <div class="flex-grow-1 d-flex align-items-center">
              <form class="w-100 me-3">
                  <input type="search" class="form-control" placeholder="Search...">
              </form>
              <div class="flex-shrink-0 dropdown">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://via.placeholder.com/28?text=!" alt="user" width="32" height="32" class="rounded-circle">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="dropdownUser2" style="">
                      <li><a class="dropdown-item" href="#">New project...</a></li>
                      <li><a class="dropdown-item" href="#">Settings</a></li>
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li>
                          <hr class="dropdown-divider">
                      </li>
                      <li><a class="dropdown-item" href="#">Sign out</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </header>
  <div class="container-fluid pb-3 flex-grow-1 d-flex flex-column flex-sm-row overflow-auto">
      <div class="row flex-grow-sm-1 flex-grow-0">
          <aside class="col-sm-3 flex-grow-sm-1 flex-shrink-1 flex-grow-0 sticky-top pb-sm-0 pb-3">
              <div class="bg-light border rounded-3 p-1 h-100 sticky-top">
                  <ul class="nav nav-pills flex-sm-column flex-row mb-auto justify-content-between text-truncate">
                      <li class="nav-item">
                          <a href="#" class="nav-link px-2 text-truncate">
                              <i class="bi bi-house fs-5"></i>
                              <span class="d-none d-sm-inline">Home</span>
                          </a>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-2 text-truncate">
                              <i class="bi bi-speedometer fs-5"></i>
                              <span class="d-none d-sm-inline">Dashboard</span>
                          </a>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-2 text-truncate"><i class="bi bi-card-text fs-5"></i>
                              <span class="d-none d-sm-inline">Orders</span> </a>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-2 text-truncate"><i class="bi bi-bricks fs-5"></i>
                              <span class="d-none d-sm-inline">Products</span> </a>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-2 text-truncate"><i class="bi bi-people fs-5"></i>
                              <span class="d-none d-sm-inline">Customers</span> </a>
                      </li>
                  </ul>
              </div>
          </aside>
          <main class="col overflow-auto h-100">
              <div class="bg-light border rounded-3 p-3">
                <h1>ooooooooooooooooo</h1>
                {% block content %}
               
                {% endblock content %}
              </div>
          </main>
      </div>
  </div>
<!-- commented -->
{% endcomment %}

    <header>
      <!-- Fixed navbar -->
      <div class="flex-md-row p-3
       mb-3 bg-dark border-bottom shadow-sm">
       <div class="row">
        <div class="col-md-2">
        <a href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">Website</a>
        </div>
        <div class="col-md-10">

        <nav class="my-md-0">
          <div class="row">
            <div class="col-md-10">

      

          <a class="btn btn-outline-primary"  href="#sidebar" data-bs-toggle="collapse"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg></a>
          <a class="btn btn-outline-primary" href="{% url 'blog:post_list' %}">Blog</a>

          <a class="btn btn-outline-primary" href="#">About</a>
        </div>
        

          <div class="col-md-2">
          <a class="btn btn-outline-primary pull-right" href="" data-bs-toggle="dropdown" aria-expanded="false"><i class="far fa-user"></i></a>

        <ul class="dropdown-menu">
            {% if user.is_authenticated %}
        
        
            <li><a class="dropdown-item" href="#">{{request.user.username}}</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'login' %}">Log In</a></li>
            <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
        
        
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Separated link</a></li>
        </ul>

          </div>

        </div>
        </nav>
      </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="row flex-nowrap">
          <div class="col-auto px-0">
              <div id="sidebar" class="collapse collapse-horizontal show border-end">
                  <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start min-vh-100">
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                      <li class="nav-item">
                          <a href="#" class="nav-link align-middle px-0">
                              <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                          </a>
                      </li>
                      <li>
                          <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                              <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                          <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                              <li class="w-100">
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
                              </li>
                              <li>
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                              </li>
                          </ul>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-0 align-middle">
                              <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                      </li>
                      <li>
                          <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                              <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
                          <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                              <li class="w-100">
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                              </li>
                              <li>
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                              </li>
                          </ul>
                      </li>
                      <li>
                          <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                              <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                              <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                              <li class="w-100">
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                              </li>
                              <li>
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                              </li>
                              <li>
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                              </li>
                              <li>
                                  <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                              </li>
                          </ul>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-0 align-middle">
                              <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                      </li>
                  </ul>

                  </div>
              </div>
          </div>
          <main class="col ps-md-2 pt-2">
              
              <div class="row">
                  <div class="col-12">
                      <div class="container-fluid">
                        {% block content %}
                        {% endblock content %}
                      </div>
                  </div>
              </div>
          </main>
      </div>
  </div>
 
    

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block javascript %}
      <script src="{% static 'js/base.js' %}"></script>
    {% endblock javascript %}
  
  </body>
</html>

Test1/templates/base_extra/front_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://kit.fontawesome.com/78ceb0f66b.js" crossorigin="anonymous"></script>
    <title>
      {% block title %} {% endblock title %}  
    </title>
    <style>
      code {
        font-family: Consolas,"courier new";
        background-color:grey;
        padding: 2px;
        font-size: 105%;
      }
      </style>

  </head>
  <body>
    <header class="py-3 mb-4 border-bottom shadow">
      <div class="container-fluid align-items-center d-flex">

        <div class="flex-grow-1 d-flex align-items-center">
            <div class="flex-shrink-0">
              
               <a href="{% url 'home' %}"  class="text-decoration-none"> <h4>EMS &nbsp;&nbsp;&nbsp;&nbsp;</h4></a>
            </div>


          <div class="flex-grow-1 d-flex align-items-space-between">
            <div class="col-md-12 d-flex">
                <div class="col-md-11 d-flex">
            
                    <div class="flex-shrink-0 ">
                        <a href="#" data-bs-target="#sidebar" data-bs-toggle="collapse"
                            class="border rounded-3 p-2 text-decoration-none"><i class="bi bi-list bi-lg py-2 p-1"></i></a>
                    </div>
                    <div class="flex-shrink-0 ">
                        <!-- <button class="btn btn-light"> Blog</button> -->
                        <a href="{% url 'blog:post_list' %}" class="border rounded-3 p-2 text-decoration-none">My Dairy</a>
                    </div>
                    <div class="flex-shrink-0 ">
                        <a href="#" class="border rounded-3 p-2 text-decoration-none">About&nbsp;&nbsp;&nbsp;&nbsp;</a>
                    </div>
                </div>
            
                <div class="col-md-1">
            
                    <div class="flex-shrink-0 dropdown ">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle pull-right" id="dropdownUser2"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <!-- <img src="https://ehsansoftware.com/img/team/nazmul.jpg" alt="user" width="32" height="32"
                                class="rounded-circle"> -->
                                <i class="bi bi-person-circle"></i>
                        </a>
            
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
            
            
                            <li><a class="dropdown-item" href="#">{{request.user.username}}</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'login' %}">Log In</a></li>
                            <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
                            {% endif %}
            
            
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Separated link</a></li>
                        </ul>
                    </div>
            
                </div>
            </div>
            <!-- <a href="#" data-bs-target="#sidebar" data-bs-toggle="collapse" class="border rounded-3 p-1 text-decoration-none"><i class="bi bi-list"></i></a> -->

          </div>
      </div>
  </header>

  <div class="container">
      {% block content %}
      
      {% endblock content %}

  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block javascript %}
      <script src="{% static 'js/base.js' %}"></script>
    {% endblock javascript %}
  
  </body>
</html>