Test1/api/urls.py
from django.urls import path, include
from .views import HomeView
urlpatterns = [
    path('',HomeView.as_view(),name ='home')
]

Test1/blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
)

app_name='blog'
urlpatterns = [
    path('posts/',PostListView.as_view(), name='post_list'),
    path('create-posts/',PostCreateView.as_view(), name='create_posts'),
    path('post-details/<int:pk>/', PostDetailView.as_view(), name='post_details'),
    path('post-update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

Test1/core/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    # path('ckeditor/',include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Test1/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from accounts.models import CustomUser
from django.urls import reverse

class Post(models.Model):
    title= models.CharField(max_length=100)
    # contentent = models.TextField()
    body = RichTextUploadingField()
    # body = RichTextField()
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)
    class Meta:
        ordering = ('-id',)
    def __str__(self):
        return self.title

    def  get_absolute_url(self):
        return reverse('blog:post_details', kwargs={'pk': self.pk})

Test1/blog/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
class PostForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField(widget=CKEditorUploadingWidget())

Test1/blog/views.py
from django.http import request
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, View
from django.urls import reverse_lazy, reverse
from blog.models import Post
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from django.core.paginator import Paginator

class PostListView(LoginRequiredMixin,View):
    def get(self, request):
        post_list = Post.objects.filter(author=request.user)
        paginator = Paginator(post_list, 2) # Show 25 contacts per page.

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'blog/post_list.html', {'page_obj': page_obj})
        
        
class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    
    # fields = '__all__'
    fields = ('title', 'body',)
    # context_object_name = 'page_obj'
    template_name='blog/post_create.html'
    login_url = reverse_lazy('login')
    # success_url = reverse_lazy('blog:post_list')
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_details', kwargs={'pk' : self.object.pk})

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PostCreateView, self).get_form_kwargs(
            *args, **kwargs)
        return kwargs

class PostDetailView(LoginRequiredMixin,DetailView):
    model = Post
    fields = '__all__'
    context_object_name = 'post'
    template_name='blog/post_details.html'
    login_url = reverse_lazy('login')
    
class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    fields = '__all__'
    context_object_name = 'post'
    template_name='blog/post_update.html'
    login_url = reverse_lazy('login')
    # success_url = reverse_lazy('blog:post_list')
    def get_success_url(self):
        return reverse('blog:post_details', kwargs={'pk' : self.object.pk})

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PostUpdateView, self).get_form_kwargs(
            *args, **kwargs)
        return kwargs
    
class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    context_object_name = 'post'
    template_name='blog/post_delete.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('blog:post_list')

Test1/templates/blog/post_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
new post
{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    

{% endblock content %}

Test1/templates/blog/post_delete.html
{% extends '_base.html' %}
{% block content %}
<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ post.title }}"?</p>
<input type="submit" value="Confirm" />
</form>
{% endblock content %}

Test1/templates/blog/post_details.html
{% extends '_base.html' %}
{% load static %}
{% block title %}
post details
{% endblock title %}

{% block content %}
<div>
    <a href="{% url 'blog:create_posts' %}">+add new post </a>
</div>

<div>
    
    <h3> Title: {{ post.title }}</h3>
    <h4> Author: {{ post.author }}</h4>
    <p> Body: {{ post.body | safe  }}</p>
</div>

<div>
    <a href="{% url 'blog:post_update' pk=post.id %}"> <button class='btn btn-primary'>Update</button> </a>
    <a href="{% url 'blog:post_delete' pk=post.id %}"> <button class='btn btn-danger'>Delete</button> </a>
</div>

{% endblock content %}

Test1/templates/blog/post_list.html
{% extends '_base.html' %}

{% block title %}
blog
{% endblock title %}

{% block content %}
<div>
    <a href="{% url 'blog:create_posts' %}">+add new post </a>
</div>

    <div>
        {% for post in page_obj %}
        <h3> Title: {{ post.title }}</h3> 
            <a href="{% url 'blog:post_details' pk=post.id %}"> <button class='btn btn-info'>Details</button> </a>
            <hr>
        {% endfor %}
    </div>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock content %}

Test1/templates/blog/post_update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
new post
{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Update</button>
    </form>
    

{% endblock content %}